/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import javax.swing.JOptionPane;

/**
 *
 * @author USer
 */
public class Dashboard extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        gradasi1 = new Menu.Gradasi();
        jL_Dashboard = new javax.swing.JLabel();
        jB_DataBarang = new javax.swing.JButton();
        jB_DataSupplier = new javax.swing.JButton();
        jB_DataMember = new javax.swing.JButton();
        jB_Pembelian = new javax.swing.JButton();
        jB_Penjualan = new javax.swing.JButton();
        jL_Judul = new javax.swing.JLabel();
        jB_Logout = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        jM_Home = new javax.swing.JMenu();
        jM_InputData = new javax.swing.JMenu();
        jM_Transaksi = new javax.swing.JMenu();
        jM_Laporan = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gradasi1.setBackground(new java.awt.Color(0, 0, 0));
        gradasi1.setForeground(new java.awt.Color(0, 0, 0));
        gradasi1.setColorEnd(new java.awt.Color(102, 255, 255));
        gradasi1.setColorStart(new java.awt.Color(0, 102, 255));

        jL_Dashboard.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/analyzing_2973762.png"))); // NOI18N

        jB_DataBarang.setBackground(new java.awt.Color(255, 255, 255));
        jB_DataBarang.setForeground(new java.awt.Color(0, 0, 0));
        jB_DataBarang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/notepad_9305568 (1).png"))); // NOI18N
        jB_DataBarang.setText("Data Barang");
        jB_DataBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DataBarangActionPerformed(evt);
            }
        });

        jB_DataSupplier.setBackground(new java.awt.Color(255, 255, 255));
        jB_DataSupplier.setForeground(new java.awt.Color(0, 0, 0));
        jB_DataSupplier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/group_1001209.png"))); // NOI18N
        jB_DataSupplier.setText("Data Supplier");
        jB_DataSupplier.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DataSupplierActionPerformed(evt);
            }
        });

        jB_DataMember.setBackground(new java.awt.Color(255, 255, 255));
        jB_DataMember.setForeground(new java.awt.Color(0, 0, 0));
        jB_DataMember.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/database_10876348.png"))); // NOI18N
        jB_DataMember.setText("Data Member");

        jB_Pembelian.setBackground(new java.awt.Color(255, 255, 255));
        jB_Pembelian.setForeground(new java.awt.Color(0, 0, 0));
        jB_Pembelian.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/sales-marketing_16977573.png"))); // NOI18N
        jB_Pembelian.setText("Pembelian");
        jB_Pembelian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PembelianActionPerformed(evt);
            }
        });

        jB_Penjualan.setBackground(new java.awt.Color(255, 255, 255));
        jB_Penjualan.setForeground(new java.awt.Color(0, 0, 0));
        jB_Penjualan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/give-money_2510743.png"))); // NOI18N
        jB_Penjualan.setText("Penjualan");
        jB_Penjualan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_PenjualanActionPerformed(evt);
            }
        });

        jL_Judul.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jL_Judul.setForeground(new java.awt.Color(255, 255, 255));
        jL_Judul.setText("APLIKASI KASHIRATAL MUSTAQIM");

        jB_Logout.setBackground(new java.awt.Color(204, 0, 0));
        jB_Logout.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Logout.setForeground(new java.awt.Color(255, 255, 255));
        jB_Logout.setText("LOG-OUT");
        jB_Logout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_LogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gradasi1Layout = new javax.swing.GroupLayout(gradasi1);
        gradasi1.setLayout(gradasi1Layout);
        gradasi1Layout.setHorizontalGroup(
            gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradasi1Layout.createSequentialGroup()
                .addGroup(gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(gradasi1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(jB_DataBarang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_DataSupplier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_DataMember)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Pembelian)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jB_Penjualan))
                    .addGroup(gradasi1Layout.createSequentialGroup()
                        .addGap(342, 342, 342)
                        .addComponent(jL_Judul)))
                .addContainerGap(313, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradasi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradasi1Layout.createSequentialGroup()
                        .addComponent(jL_Dashboard)
                        .addGap(509, 509, 509))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradasi1Layout.createSequentialGroup()
                        .addComponent(jB_Logout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(583, 583, 583))))
        );
        gradasi1Layout.setVerticalGroup(
            gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradasi1Layout.createSequentialGroup()
                .addGap(112, 112, 112)
                .addComponent(jL_Judul)
                .addGap(29, 29, 29)
                .addComponent(jL_Dashboard)
                .addGap(28, 28, 28)
                .addGroup(gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jB_DataBarang)
                    .addComponent(jB_DataSupplier)
                    .addComponent(jB_DataMember)
                    .addComponent(jB_Pembelian)
                    .addComponent(jB_Penjualan))
                .addGap(18, 18, 18)
                .addComponent(jB_Logout)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jM_Home.setText("Home");
        jM_Home.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_HomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_Home);

        jM_InputData.setText("Input Data");
        jM_InputData.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_InputDataMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_InputData);

        jM_Transaksi.setText("Transaksi");
        jM_Transaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jM_TransaksiMouseClicked(evt);
            }
        });
        jMenuBar1.add(jM_Transaksi);

        jM_Laporan.setText("Laporan");
        jMenuBar1.add(jM_Laporan);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jB_DataBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DataBarangActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jB_DataBarangActionPerformed

    private void jB_PembelianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PembelianActionPerformed
        // TODO add your handling code here:
        Pembelian brg = new Pembelian();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_PembelianActionPerformed

    private void jB_PenjualanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_PenjualanActionPerformed
        // TODO add your handling code here:
        Penjualan brg = new Penjualan();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_PenjualanActionPerformed

    private void jM_HomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_HomeMouseClicked
        // TODO add your handling code here:
        Dashboard brg = new Dashboard();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jM_HomeMouseClicked

    private void jB_LogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_LogoutActionPerformed
        // TODO add your handling code here:
        int dialogBtn = JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this,
                "Apakah anda yakin ingin keluar", "PERINGATAN", dialogBtn);
        if (dialogResult == 0) {
            Login n = new Login();
            n.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_jB_LogoutActionPerformed

    private void jB_DataSupplierActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DataSupplierActionPerformed
        // TODO add your handling code here:
        Supplier brg = new Supplier();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jB_DataSupplierActionPerformed

    private void jM_InputDataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_InputDataMouseClicked
        // TODO add your handling code here:
        Supplier brg = new Supplier();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jM_InputDataMouseClicked

    private void jM_TransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jM_TransaksiMouseClicked
        // TODO add your handling code here:
        Penjualan brg = new Penjualan();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jM_TransaksiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private Menu.Gradasi gradasi1;
    private javax.swing.JButton jB_DataBarang;
    private javax.swing.JButton jB_DataMember;
    private javax.swing.JButton jB_DataSupplier;
    private javax.swing.JButton jB_Logout;
    private javax.swing.JButton jB_Pembelian;
    private javax.swing.JButton jB_Penjualan;
    private javax.swing.JLabel jL_Dashboard;
    private javax.swing.JLabel jL_Judul;
    private javax.swing.JMenu jM_Home;
    private javax.swing.JMenu jM_InputData;
    private javax.swing.JMenu jM_Laporan;
    private javax.swing.JMenu jM_Transaksi;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
