/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Menu;

import java.sql.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.Driver;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USer
 */
public class Supplier extends javax.swing.JFrame {

    /**
     * Creates new form Dashboard
     */
    public Supplier() {
        initComponents();
        tampilkan();
    }

    private void tampilkan() {
        DefaultTableModel model = new DefaultTableModel();
        model.setColumnIdentifiers(new Object[]{
            "ID", "Kode Supplier", "Nama Perusahaan", "Barang Dijual", "No. Telp", "Alamat"
        });
        TB_Supplier.setModel(model);

        try {
            Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashiratal_mustaqim", "root", "");
            String query = "SELECT id, kode_supplier, nama_perusahaan, barang_dijual, no_tlp, alamat FROM supplier";
            PreparedStatement stmt = conn.prepareStatement(query);
            ResultSet rs = stmt.executeQuery();

            while (rs.next()) {
                String id = rs.getString("id");
                String kode_supplier = rs.getString("kode_supplier");
                String nama_perusahaan = rs.getString("nama_perusahaan");
                String barang_dijual = rs.getString("barang_dijual");
                String no_tlp = rs.getString("no_tlp");
                String alamat = rs.getString("alamat");

                model.addRow(new Object[]{
                    id, kode_supplier, nama_perusahaan, barang_dijual, no_tlp, alamat
                });
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat data supplier: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        gradasi1 = new Menu.Gradasi();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        kd_sup = new javax.swing.JTextField();
        nm_p = new javax.swing.JTextField();
        barjul = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        no_tlp = new javax.swing.JTextField();
        alamat = new javax.swing.JTextField();
        jB_Save = new javax.swing.JButton();
        jB_Edit = new javax.swing.JButton();
        jB_Clear = new javax.swing.JButton();
        jB_Delete = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TB_Supplier = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();

        jMenu3.setText("File");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("Edit");
        jMenuBar2.add(jMenu4);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        gradasi1.setBackground(new java.awt.Color(0, 0, 0));
        gradasi1.setForeground(new java.awt.Color(0, 0, 0));
        gradasi1.setColorEnd(new java.awt.Color(102, 255, 255));
        gradasi1.setColorStart(new java.awt.Color(0, 102, 255));
        gradasi1.setPreferredSize(new java.awt.Dimension(1280, 680));

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Supplier");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1195, 555));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 0, 0));
        jLabel6.setText("Barang Di Jual");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 0, 0));
        jLabel7.setText("Nama Perusahaan");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(0, 0, 0));
        jLabel8.setText("Kode Supplier");

        barjul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                barjulActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setText("No. Tlp");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(0, 0, 0));
        jLabel16.setText("Alamat");

        no_tlp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                no_tlpActionPerformed(evt);
            }
        });

        jB_Save.setBackground(new java.awt.Color(0, 153, 0));
        jB_Save.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Save.setForeground(new java.awt.Color(255, 255, 255));
        jB_Save.setText("SAVE");
        jB_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_SaveActionPerformed(evt);
            }
        });

        jB_Edit.setBackground(new java.awt.Color(153, 153, 0));
        jB_Edit.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Edit.setForeground(new java.awt.Color(255, 255, 255));
        jB_Edit.setText("EDIT");
        jB_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_EditActionPerformed(evt);
            }
        });

        jB_Clear.setBackground(new java.awt.Color(51, 51, 51));
        jB_Clear.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Clear.setForeground(new java.awt.Color(255, 255, 255));
        jB_Clear.setText("CLEAR");
        jB_Clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_ClearActionPerformed(evt);
            }
        });

        jB_Delete.setBackground(new java.awt.Color(153, 0, 0));
        jB_Delete.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jB_Delete.setForeground(new java.awt.Color(255, 255, 255));
        jB_Delete.setText("DELETE");
        jB_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jB_DeleteActionPerformed(evt);
            }
        });

        TB_Supplier.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "No", "Kode Supplier", "Nama Perusahaan", "Barang Di Jual", "No. Tlp", "Alamat"
            }
        ));
        TB_Supplier.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TB_SupplierMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(TB_Supplier);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(68, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8))
                        .addGap(151, 151, 151)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(barjul, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                            .addComponent(nm_p, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(kd_sup, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel15)
                                    .addComponent(jLabel16))
                                .addGap(68, 68, 68)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(alamat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(no_tlp)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jB_Save)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jB_Edit)
                                .addGap(18, 18, 18)
                                .addComponent(jB_Clear)
                                .addGap(18, 18, 18)
                                .addComponent(jB_Delete)))))
                .addContainerGap(69, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(53, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kd_sup)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15)
                    .addComponent(no_tlp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nm_p)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(alamat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(barjul, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jB_Save)
                    .addComponent(jB_Edit)
                    .addComponent(jB_Clear)
                    .addComponent(jB_Delete))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 319, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(54, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout gradasi1Layout = new javax.swing.GroupLayout(gradasi1);
        gradasi1.setLayout(gradasi1Layout);
        gradasi1Layout.setHorizontalGroup(
            gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradasi1Layout.createSequentialGroup()
                .addContainerGap(40, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(45, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, gradasi1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(571, 571, 571))
        );
        gradasi1Layout.setVerticalGroup(
            gradasi1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gradasi1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jMenu1.setText("Home");
        jMenu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu1MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Input Data");
        jMenu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu2MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu2);

        jMenu5.setText("Transaksi");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        jMenu6.setText("Laporan");
        jMenuBar1.add(jMenu6);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(gradasi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(gradasi1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu1MouseClicked
        // TODO add your handling code here:
        Dashboard brg = new Dashboard();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu1MouseClicked

    private void barjulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_barjulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_barjulActionPerformed

    private void jMenu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu2MouseClicked
        // TODO add your handling code here:
        Supplier brg = new Supplier();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu2MouseClicked

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        Penjualan brg = new Penjualan();
        brg.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu5MouseClicked

    private void jB_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_SaveActionPerformed
        // TODO add your handling code here:
        if (!validateInput()) {
            return;
        }
        saveData();
        tampilkan();
    }//GEN-LAST:event_jB_SaveActionPerformed

    private void no_tlpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_no_tlpActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_no_tlpActionPerformed

    private void jB_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_DeleteActionPerformed
        // TODO add your handling code here:
        int selectedRow = TB_Supplier.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus!");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) TB_Supplier.getModel();
// Ambil ID dari kolom pertama (kolom ke-0)
        String idSupplier = model.getValueAt(selectedRow, 0).toString();

// Konfirmasi penghapusan
        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            try {
                // Hapus data dari database berdasarkan ID
                Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashiratal_mustaqim", "root", "");
                String query = "DELETE FROM supplier WHERE id = ?";
                PreparedStatement ps = conn.prepareStatement(query);
                ps.setString(1, idSupplier);
                ps.executeUpdate();

                // Hapus baris dari tabel
                model.removeRow(selectedRow);

                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } catch (SQLException e) {
                JOptionPane.showMessageDialog(this, "Kesalahan saat menghapus data: " + e.getMessage());
            }
        }

    }//GEN-LAST:event_jB_DeleteActionPerformed

    private void jB_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_EditActionPerformed
        // TODO add your handling code here: 
        String kode_supplier = kd_sup.getText().trim(); // read-only, tidak bisa diedit user
        String nama_perusahaan = nm_p.getText().trim();
        String barang_dijual = barjul.getText().trim();
        String notlp = no_tlp.getText().trim();
        String almt = alamat.getText().trim();

// Kode untuk koneksi ke database
        Connection conn = null;
        PreparedStatement pst = null;

        try {
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashiratal_mustaqim", "root", "");

            // SQL query tanpa update ID dan kode_supplier
            String sql = "UPDATE supplier SET nama_perusahaan = ?, barang_dijual = ?, no_tlp = ?, alamat = ? WHERE kode_supplier = ?";

            pst = conn.prepareStatement(sql);
            pst.setString(1, nama_perusahaan);
            pst.setString(2, barang_dijual);
            pst.setString(3, notlp);
            pst.setString(4, almt);
            pst.setString(5, kode_supplier); // dipakai sebagai WHERE

            int updatedRows = pst.executeUpdate();

            if (updatedRows > 0) {
                JOptionPane.showMessageDialog(this, "Data berhasil diperbarui!", "Sukses", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan untuk diupdate!", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (pst != null) {
                    pst.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }

        tampilkan(); // Refresh tabel

    }//GEN-LAST:event_jB_EditActionPerformed

    private void jB_ClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jB_ClearActionPerformed
        // TODO add your handling code here:
        kd_sup.setText("");
        nm_p.setText("");
        barjul.setText("");
        no_tlp.setText("");
        alamat.setText("");
        kd_sup.enable(true);
        tampilkan();
    }//GEN-LAST:event_jB_ClearActionPerformed

    private void TB_SupplierMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TB_SupplierMouseClicked
        // TODO add your handling code here:
        int selectedRow = TB_Supplier.getSelectedRow();

// Mengambil data berdasarkan urutan kolom yang baru
        String id = TB_Supplier.getValueAt(selectedRow, 0).toString();              // Kolom 0: ID
        String kode_supplier = TB_Supplier.getValueAt(selectedRow, 1).toString();   // Kolom 1: Kode Supplier
        String nama_perusahaan = TB_Supplier.getValueAt(selectedRow, 2).toString(); // Kolom 2: Nama Perusahaan
        String barang_dijual = TB_Supplier.getValueAt(selectedRow, 3).toString();   // Kolom 3: Barang Dijual
        String no_tlp = TB_Supplier.getValueAt(selectedRow, 4).toString();          // Kolom 4: No. Telp
        String alamat = TB_Supplier.getValueAt(selectedRow, 5).toString();          // Kolom 5: Alamat

// Tampilkan ke text field
        kd_sup.setText(kode_supplier);
        nm_p.setText(nama_perusahaan);
        barjul.setText(barang_dijual);
        this.no_tlp.setText(no_tlp);
        this.alamat.setText(alamat);

    }//GEN-LAST:event_TB_SupplierMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Supplier.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Supplier().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TB_Supplier;
    private javax.swing.JTextField alamat;
    private javax.swing.JTextField barjul;
    private Menu.Gradasi gradasi1;
    private javax.swing.JButton jB_Clear;
    private javax.swing.JButton jB_Delete;
    private javax.swing.JButton jB_Edit;
    private javax.swing.JButton jB_Save;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTextField kd_sup;
    private javax.swing.JTextField nm_p;
    private javax.swing.JTextField no_tlp;
    // End of variables declaration//GEN-END:variables

    private boolean validateInput() {
        if (kd_sup.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Kode Supplier tidak boleh kosong");
            return false;
        }
        if (nm_p.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Nama Perusahaan tidak boleh kosong");
            return false;
        }
        if (barjul.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Barang di Jual tidak boleh kosong");
            return false;
        }
        if (no_tlp.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "No. Telp tidak boleh kosong");
            return false;
        }
        if (alamat.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Alamat tidak boleh kosong");
            return false;
        }
        return true;
    }

    private void saveData() {
        if (!validateInput()) {
            return; // Hentikan jika input tidak valid
        }

        String query = "INSERT INTO supplier (kode_supplier, nama_perusahaan, barang_dijual, no_tlp, alamat) VALUES (?, ?, ?, ?, ?)";

        try (
                Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/kashiratal_mustaqim", "root", ""); PreparedStatement ps = con.prepareStatement(query)) {
            ps.setString(1, kd_sup.getText().trim());
            ps.setString(2, nm_p.getText().trim());
            ps.setString(3, barjul.getText().trim());
            ps.setString(4, no_tlp.getText().trim());
            ps.setString(5, alamat.getText().trim());

            ps.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data supplier berhasil disimpan!");

            // Kosongkan semua input field
            kd_sup.setText("");
            nm_p.setText("");
            barjul.setText("");
            no_tlp.setText("");
            alamat.setText("");

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }
}
